apiVersion: v1
kind: Config
clusters:
- name: default
  cluster:
    certificate-authority-data: <certificate-authority-data>
    server: https://127.0.0.1:6443
contexts:
- name: traefik@default
  context:
    cluster: default
    user: traefik
current-context: traefik@default
users:
- name: traefik
  user:
    token: <token>
